workflows:
  ios-prod:
    name: Athletica iOS Production Simulator
    instance_type: mac_mini_m2

    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: master
          include: true
          source: true
      tag_patterns:
        - pattern: v*
          include: true

    environment:
      flutter: 3.41.6
    groups:
      - athletica_ios_prod  

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..

      - name: Prepare environment files
        script: |
          cat > .env.prod <<EOF
          BASE_URL=$BASE_URL
          APP_NAME=$APP_NAME
          SENTRY_DSN=$SENTRY_DSN
          EOF

          touch .env.dev

      - name: Analyze Flutter project
        script: flutter analyze

      - name: Run tests
        script: |
          if find test -type f -name '*_test.dart' | grep -q .; then
            flutter test
          else
            echo "No Flutter tests found. Skipping tests."
          fi

      - name: Build iOS Simulator Release
        script: |
          flutter build ios \
            --simulator \
            --release \
            --target lib/main_prod.dart

      - name: Package iOS Simulator app
        script: |
          cd build/ios/iphonesimulator
          zip -r Runner.zip Runner.app

    artifacts:
      - build/ios/iphonesimulator/Runner.zip