class FoodItem {
  const FoodItem({
    required this.id,
    required this.name,
    required this.emoji,
    required this.category,
    required this.serving,
    required this.calories,
    required this.proteinGrams,
    required this.carbsGrams,
    required this.fatGrams,
  });

  final String id;
  final String name;
  final String emoji;
  final String category;
  final String serving;
  final int calories;
  final int proteinGrams;
  final int carbsGrams;
  final int fatGrams;
}

abstract class FoodItemsData {
  static const List<FoodItem> all = [
    FoodItem(
      id: 'f1',
      name: 'Chicken Breast',
      emoji: '🍗',
      category: 'Protein',
      serving: '100g',
      calories: 165,
      proteinGrams: 31,
      carbsGrams: 0,
      fatGrams: 4,
    ),
    FoodItem(
      id: 'f2',
      name: 'Chicken Thigh',
      emoji: '🍖',
      category: 'Protein',
      serving: '100g',
      calories: 180,
      proteinGrams: 27,
      carbsGrams: 0,
      fatGrams: 8,
    ),
    FoodItem(
      id: 'f3',
      name: 'Beef Steak',
      emoji: '🥩',
      category: 'Protein',
      serving: '100g',
      calories: 250,
      proteinGrams: 26,
      carbsGrams: 0,
      fatGrams: 15,
    ),
    FoodItem(
      id: 'f4',
      name: 'Minced Meat',
      emoji: '🥩',
      category: 'Protein',
      serving: '100g',
      calories: 280,
      proteinGrams: 20,
      carbsGrams: 0,
      fatGrams: 22,
    ),
    FoodItem(
      id: 'f5',
      name: 'Salmon',
      emoji: '🐟',
      category: 'Protein',
      serving: '100g',
      calories: 208,
      proteinGrams: 20,
      carbsGrams: 0,
      fatGrams: 13,
    ),
    FoodItem(
      id: 'f6',
      name: 'Tuna',
      emoji: '🐠',
      category: 'Protein',
      serving: '100g',
      calories: 132,
      proteinGrams: 29,
      carbsGrams: 0,
      fatGrams: 1,
    ),
    FoodItem(
      id: 'f7',
      name: 'Eggs',
      emoji: '🥚',
      category: 'Protein',
      serving: '2 eggs',
      calories: 155,
      proteinGrams: 13,
      carbsGrams: 1,
      fatGrams: 11,
    ),
    FoodItem(
      id: 'f8',
      name: 'Rice',
      emoji: '🍚',
      category: 'Carb',
      serving: '1 cup',
      calories: 200,
      proteinGrams: 4,
      carbsGrams: 45,
      fatGrams: 1,
    ),
    FoodItem(
      id: 'f9',
      name: 'Oats',
      emoji: '🌾',
      category: 'Carb',
      serving: '1 cup (80)',
      calories: 300,
      proteinGrams: 10,
      carbsGrams: 54,
      fatGrams: 6,
    ),
    FoodItem(
      id: 'f10',
      name: 'Sweet Potato',
      emoji: '🍠',
      category: 'Carb',
      serving: '1 medium',
      calories: 112,
      proteinGrams: 2,
      carbsGrams: 26,
      fatGrams: 0,
    ),
    FoodItem(
      id: 'f11',
      name: 'Broccoli',
      emoji: '🥦',
      category: 'Carb',
      serving: '1 cup',
      calories: 55,
      proteinGrams: 4,
      carbsGrams: 11,
      fatGrams: 1,
    ),
    FoodItem(
      id: 'f12',
      name: 'Greek Yogurt',
      emoji: '🥛',
      category: 'Protein',
      serving: '1 cup',
      calories: 130,
      proteinGrams: 10,
      carbsGrams: 12,
      fatGrams: 3,
    ),
    FoodItem(
      id: 'f13',
      name: 'Almonds',
      emoji: '🌰',
      category: 'Nuts',
      serving: '10 pieces (15)',
      calories: 60,
      proteinGrams: 2,
      carbsGrams: 2,
      fatGrams: 5,
    ),
    FoodItem(
      id: 'f14',
      name: 'Avocado',
      emoji: '🥑',
      category: 'Fat',
      serving: '1/2 medium',
      calories: 160,
      proteinGrams: 2,
      carbsGrams: 9,
      fatGrams: 15,
    ),
  ];
}
